/*This service contains the common functions used across various controllers*/

controlCenterConsoleApp.factory('commonFunctionService', 
	[
	function(){

		var keywordArray = [
		"allow", 
		"deny" , 
		"windowsSid", 
		"unixId", 
		"principalName", 
		"mail", 
		"lastName", 
		"firstName", 
		"displayname",
		"access_control",
		"access_policy",
		"action",
		"action_entity",
		"allow_overrides",
		"allowed_entities",
		"all",
		"and",
		"application",
		"application_entity",
		"attribute",
		"by",
		"call_function",
		"combine",
		"component",
		"confirm",
		"creator",
		"default",
		"deny_overrides",
		"deployed",
		"description",
		"device_entity",
		"do",
		"does_not_have",
		"dontlog",
		"enovia_entity",
		// "email",
		"empty",
		"equals_unordered",
		"subpolicy",
		"false",
		"folder",
		"for",
		"has",
		"hidden",
		"host",
		"host_entity",
		"id",
		// "im",
		"in",
		"includes",
		"local",
		"location",
		"location_entity",
		"log",
		"matches",
		"not",
		"notify",
		"null",
		"on",
		"or",
		"pbac",
		"policy",
		"policy_entity",
		"portal_entity",
		"principal",
		"query",
		"quiet",
		"recipient",
		"resource",
		"resource_entity",
		"rule",
		"sap_entity",
		"severity",
		"sent_to",
		"status",
		"tag",
		"tags",
		"to",
		"true",
		"dontcare",
		"using",
		"user",
		"user_entity",
		"where",
		"with"
];
		var isPQLReservedKeyword = function(inputStr){
			return keywordArray.indexOf(inputStr) === -1 ? 0: 1;
		}	

		return {
			isPQLReservedKeyword: isPQLReservedKeyword
		}
	}
	]);